[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.3.1", default-features = false, features = ["macros"] }
file-fetch = { path = "../file-fetch" }

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3