[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.4"
include_dir = "0.7.3"
mime_guess = "2.0.4"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }